name: Validate and Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18 # ou sua versão atual do Node

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      - name: Trigger Render Deploy
        if: success()  # Só executa se o build foi bem-sucedido
        run: |
          curl -X POST "https://api.render.com/deploy/srv-XXXXXX?key=YYYYYY"
